daytona:
    api_key: ENC[AES256_GCM,data:wDw/RPIG6PRAxzM1TxwV07hNNJ4TjSIPKg8pDOHTBSUlV+8TFZizfT975iSH9KjkCtIF+j8oe/GGujZAvpdrCqKWLno=,iv:PVRgnjINmsDnL0KzZ2uhlaREz6pPsIz/upVS0ewpPVs=,tag:pZd/LEcxbZCmhKFW0V1Kkw==,type:str]
    api_url: ENC[AES256_GCM,data:5vdL31BhkcXdNLdWwnJxDVB0KaZbZN9b1Wc=,iv:bKGy+f+b6XnjIEOSUgQ/PC7UBZy7XxsEoDRzkmY6m8g=,tag:R4O5qX+AZbY043MgsfF93A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0N1Btd1FRRGNMeTFaRG5W
            Z29aZ2MrZDZqTFJWM0FOZlRtWnZBQWZYeVVBClZ0TS9lWDY4U1dsUlVlQnhoaWFB
            aFhKU2VSSDQva1NuUmRKNHNtZ3VKcGcKLS0tIGNjNk03K09ET3d6QUJqUTFoRW5t
            VGxoVXlxRHlRTExSL0pvMVFzMTM4YzAK/m5c5dVwV7ZOBGmiLmJ36nf3av24S9s9
            wy6t0NPWBrRoKnnsVY3eIi7YFI8Ob4/jsbGXv+2l5SeFnJhFIby/Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19wu83nv0pc4an6k39fjck3hhlwdw5fglfsj5jtzrc52pj8s4j3mqyh8jfq
    lastmodified: "2026-07-24T01:42:42Z"
    mac: ENC[AES256_GCM,data:iA9xbYRX0RlEijxKuBVDIRt84PSd/VceyGy01W/vxeTqE5WQLa0W8oDA3Omm2RU0K2bFKTJaY+yyJMlkLpISdsveLFI9FU1C+3aGfqcMz7GdFL8JF8RIWirTP4xfxz+CnGUHINEKKHhF1UCjwiT1wOTNwkpcbrc9fqqH7ClN+KM=,iv:alF7ffaa+uCIRWKvs9Wp92hGdZnmTlZUz7Z7spGRvX0=,tag:Diptbd2d9sLVktaBsmRuvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
