[package]
name = "baud-tape-local"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
baud-tape = { path = "../baud-tape" }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
async-trait = "0.1"

[dev-dependencies]
tokio = { workspace = true }
