[package]
name = "baud-tape"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
baud-secret = { path = "../baud-secret" }
baud-proto = { path = "../baud-proto" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
async-trait = "0.1"

[dev-dependencies]
tokio = { workspace = true }
