// Copyright (c) 2026 Henrique Falconer. All rights reserved.
// SPDX-License-Identifier: Proprietary
//
// baud spec — spec management commands

use anyhow::Result;
use clap::{Parser, Subcommand};
use serde_json::json;
use crate::{client::Client, fmt};

#[derive(Parser)]
pub struct SpecCmd {
    #[command(subcommand)]
    pub action: SpecAction,
}

#[derive(Subcommand)]
pub enum SpecAction {
    /// Create a new spec file template
    New {
        /// Workload name
        name: String,
        /// Output path (default: <name>.yaml)
        #[arg(long, short)]
        output: Option<String>,
    },
    /// Lint a spec file
    Lint {
        /// Path to spec file (YAML)
        path: String,
    },
    /// Show a spec file (parsed)
    Show {
        /// Path to spec file (YAML)
        path: String,
    },
}

pub async fn run(cmd: SpecCmd, c: &Client, json: bool) -> Result<()> {
    match cmd.action {
        SpecAction::New { name, output } => {
            let out_path = output.unwrap_or_else(|| format!("{name}.yaml"));
            let template = generate_template(&name);
            std::fs::write(&out_path, &template)?;
            if json {
                let v = json!({ "ok": true, "path": out_path, "name": name });
                fmt::print(&v, true);
            } else {
                println!("Created spec template: {out_path}");
                println!("Edit it and run: baud spec lint {out_path}");
            }
        }
        SpecAction::Lint { path } => {
            let content = read_spec_file(&path)?;
            let body = json!({ "content": content });
            let v = c.post("/spec/lint", &body).await?;
            let ok = v.get("ok").and_then(|v| v.as_bool()).unwrap_or(false);
            fmt::print(&v, json);
            if !ok {
                std::process::exit(1);
            }
        }
        SpecAction::Show { path } => {
            let content = read_spec_file(&path)?;
            let body = json!({ "content": content });
            let v = c.post("/spec/show", &body).await?;
            fmt::print(&v, json);
            if v.get("error").is_some() {
                std::process::exit(1);
            }
        }
    }
    Ok(())
}

fn read_spec_file(path: &str) -> Result<String> {
    std::fs::read_to_string(path)
        .map_err(|e| anyhow::anyhow!("failed to read spec file '{}': {}", path, e))
}

fn generate_template(name: &str) -> String {
    format!(
        r#"# baud workload spec: {name}
# Generated by: baud spec new {name}
#
# Five directive kinds: nix, files, env, nodes, adapters
# Closed adapter set: stdin, fifo, net (input); stdout-kv, vfs-file,
#   syscall-counter, ebpf-counter, exit-hash (probe); frame (display)

nix: "./flake.nix#{name}"

env:
  RUST_BACKTRACE: "0"

nodes:
  - name: n0
    argv: ["{name}"]
    adapters:
      input: stdin
      probes:
        - stdout-kv
        - exit-hash
"#
    )
}
